### PR TITLE
fix: support Keycloak 26.6.3 Cors API (allowedOrigins -> checkAllowedOrigins)

### PR DESCRIPTION
**Pull request by JonShawTCP**
## Summary

On Keycloak 26.6.3, every Organizations admin endpoint fails with:

```
java.lang.NoSuchMethodError: 'org.keycloak.services.cors.Cors org.keycloak.services.cors.Cors.allowedOrigins(org.keycloak.representations.AccessToken)'
    at io.phasetwo.service.resource.AbstractAdminResource.setupCors(AbstractAdminResource.java:74)
```

Keycloak 26.6.3 renamed the `Cors` builder method `allowedOrigins(...)` -> `checkAllowedOrigins(...)` as part of admin CORS/CSRF hardening (keycloak/keycloak#45957). `allowedOrigins(AccessToken)` no longer exists, so `AbstractAdminResource.setupCors()` throws `NoSuchMethodError` at runtime. The extension works on Keycloak <= 26.6.2.

## Change

- `AbstractAdminResource.setupCors()`: `allowedOrigins(auth.getToken())` -> `checkAllowedOrigins(auth.getToken())`
- `pom.xml`: `keycloak.version` `26.6.1` -> `26.6.3`

## Compatibility

`checkAllowedOrigins` does not exist before 26.6.3, so this targets **26.6.3+** and is not backwards-compatible with 26.6.2 and earlier.

### CODE REVIEW

**Review by xgp — APPROVED** [review]
Thanks.
